# Generated by Django 4.2.6 on 2023-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('visits', models.IntegerField()),
                ('team_presence', models.BooleanField()),
            ],
        ),
    ]
