# Generated by Django 4.2.6 on 2023-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
