# Generated by Django 4.2.6 on 2023-10-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_status', '0002_project_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='--null--', max_length=200),
        ),
    ]
