# Generated by Django 4.2.6 on 2023-10-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_status', '0003_alter_project_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
